# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='approval_at',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='approval_reason',
            new_name='approved_reason',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='approval_by',
            new_name='approver',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='approvalstate',
        ),
        migrations.AddField(
            model_name='approval',
            name='approved',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='state',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Assigned'), (2, 'Finished')], db_index=True, default=0, editable=False),
        ),
    ]
