# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_auto_20170311_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'verbose_name': 'Approval', 'verbose_name_plural': 'Approvals'},
        ),
        migrations.AlterField(
            model_name='approval',
            name='state',
            field=models.IntegerField(choices=[(0, 'REQUESTED'), (1, 'ASSIGNED'), (2, 'FINISHED')], db_index=True, default=0, editable=False),
        ),
    ]
